import { v4 as uuid } from "uuid";
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/x/i/q/s-wx-d-pocket-102-grey-woxen-original-imagmb2ejntmmc2f.jpeg?q=70",
    _id: uuid(),
    title: "Collar casual shirt",
    author: "js garments",
    price: "429",
    categoryName: "Men",

    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/kykgb680/fabric/o/n/s/yes-2-m-unstitched-2-2-m-inithi-1478-inithi-original-imagart5bfuyyy4e.jpeg?q=70",
    _id: uuid(),
    title: "suit printed ",
    author: "inithi",
    price: "969",
    categoryName: "Women",
    ratting: "b",
  },

  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-top/1/l/s/7-8-years-20-20-pink-2-3-y-cruck-original-imagpbbws3kswghn.jpeg?q=70",
    _id: uuid(),
    title: "girls casual dress",
    author: "cruck",
    price: "669",
    categoryName: "Kids ",
    ratting: "a",
  },

  {
    src: "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8bWVuJTIwamVhbnN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    _id: uuid(),
    title: "men blue jens",
    author: "anvigarments",
    price: "1369",
    categoryName: "Men",

    ratting: "c",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-kids-dress/3/1/t/6-7-years-bag-one-shoulder-mullick-the-designer-original-imaggrn5gsxydngh.jpeg?q=70",
    _id: uuid(),
    title: "midi casul dress",
    author: "mullick ",
    price: "369",
    categoryName: "Kids",
    ratting: "b",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/c/8/j/l-ausk0184-ausk-original-imaghzdmv4fpzte6.jpeg?q=70",
    _id: uuid(),
    title: "dark green t-shirt",
    author: "ausk",
    price: "1229",
    categoryName: "Men",

    ratting: "c",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/l4x2rgw0/kids-dress/p/r/y/4-5-years-frock-0001-new-collections-original-imagfpn6fmbyu5ez.jpeg?q=70",
    _id: uuid(),
    title: "length casual dress",
    author: "nazrana",
    price: "769",
    categoryName: "Kids",
    ratting: "a",
  },
  {
    src: "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8bWVuJTIwamVhbnN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    _id: uuid(),
    title: "jeans",
    author: "classic",
    price: "5000",
    categoryName: "Women",
    ratting: "c",
  },
  {
    src: "https://media.istockphoto.com/id/1014074006/photo/denim-lets-get-back-to-basics.webp?b=1&s=170667a&w=0&k=20&c=H9GW92JA1PYL6ZMp242SFnconlEUawm5KJ-bP7Lnexg=",
    _id: uuid(),
    title: "jeans casual",
    author: "nidhi",
    price: "3000",
    categoryName: "Women",
    ratting: "d",
  },
  {
    src: "https://media.istockphoto.com/id/1352728757/photo/jean-jacket-isolated-on-white-front-and-back-views-ready-for-clipping-path.webp?b=1&s=170667a&w=0&k=20&c=6JxjG-1I_wVvQIzoKKq5q8uC6TFPsILvZRDlpH4UPRI=",
    _id: uuid(),
    title: "Men jeans",
    author: "Shiv Khera",
    price: "1000",
    categoryName: "Men",

    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/x/i/q/s-wx-d-pocket-102-grey-woxen-original-imagmb2ejntmmc2f.jpeg?q=70",
    _id: uuid(),
    title: "Collar casual shirt",
    author: "Shiv Khera",
    price: "429",
    categoryName: "Men",

    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/m/o/t/l-st1-vebnor-original-imagmsyxhvkrfjgz.jpeg?q=70",
    _id: uuid(),
    title: "Mandarin Collar shirt",
    author: "Webnor",
    price: "369",
    categoryName: "Men",

    ratting: "c",
  },
  // {
  //   src:"https://ha-clothing.netlify.app/static/media/i3.e1ab4c51.webp",
  //   _id: uuid(),
  //   title: "INDIE PICKS",
  //   author: "Anahat Handblock Kurta",
  //   price: "369",
  // },

  {
    src: "https://rukminim2.flixcart.com/image/612/612/l4oi4cw0/shirt/l/q/j/xl-4000-combraided-original-imagfgzgjt88qhjn.jpeg?q=70",
    _id: uuid(),
    title: "Fir striped casual shirt",
    author: "COMBRAIDED",
    price: "800",
    categoryName: "Men",

    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/o/s/7/28-pbwc-001-qarsh-original-imagh8cfhc3dreq8.jpeg?q=70",
    _id: uuid(),
    title: "Rise black jeans",
    author: "QARSH",
    price: "410",
    categoryName: "Men",

    ratting: "b",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/x/i/q/s-wx-d-pocket-102-grey-woxen-original-imagmb2ejntmmc2f.jpeg?q=70",
    _id: uuid(),
    title: "Collar casual shirt",
    author: "Shiv Khera",
    price: "429",
    categoryName: "Men",

    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/kz3118w0/kurta/3/w/d/l-ber3308-nayo-original-imagb6cxmpvhzxcb.jpeg?q=70",
    _id: uuid(),
    title: "Women printed Dress",
    author: "Nayo",
    price: "789",
    categoryName: "Women",
    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/g/h/g/l-usshtfx0027-u-s-polo-assn-original-imagkv3d9rqppkhh.jpeg?q=70",
    _id: uuid(),
    title: "Fit solid shirt",
    author: "U.S. POLO",
    price: "1769",
    categoryName: "Men",

    ratting: "d",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/x/i/q/s-wx-d-pocket-102-grey-woxen-original-imagmb2ejntmmc2f.jpeg?q=70",
    _id: uuid(),
    title: "Collar casual shirt",
    author: "Shiv Khera",
    price: "429",
    categoryName: "Men",

    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/kykgb680/fabric/o/n/s/yes-2-m-unstitched-2-2-m-inithi-1478-inithi-original-imagart5bfuyyy4e.jpeg?q=70",
    _id: uuid(),
    title: "suit printed ",
    author: "inithi",
    price: "969",
    categoryName: "Women",
    ratting: "a",
  },

  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-top/1/l/s/7-8-years-20-20-pink-2-3-y-cruck-original-imagpbbws3kswghn.jpeg?q=70",
    _id: uuid(),
    title: "girls casual dress",
    author: "cruck",
    price: "669",
    categoryName: "Kids",
    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-top/1/l/s/7-8-years-20-20-pink-2-3-y-cruck-original-imagpbbws3kswghn.jpeg?q=70",
    _id: uuid(),
    title: "girls casual dress",
    author: "cruck",
    price: "669",
    categoryName: "Kids",
    ratting: "b",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-top/1/l/s/7-8-years-20-20-pink-2-3-y-cruck-original-imagpbbws3kswghn.jpeg?q=70",
    _id: uuid(),
    title: "girls casual dress",
    author: "cruck",
    price: "669",
    categoryName: "Kids",
    ratting: "a",
  },

  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/a/g/q/30-88465plb-anvigarments-original-imagrqhycbydgrdr.jpeg?q=70",
    _id: uuid(),
    title: "men blue jens",
    author: "anvigarments",
    price: "1369",
    categoryName: "Woxen",
    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/2/9/y/m-bylrn-z31-blive-original-imaggdk9bjtk2hf4.jpeg?q=70",
    _id: uuid(),
    title: "light balue t-shirt",
    author: "blive",
    price: "669",
    categoryName: "Men",

    ratting: "c",
  },

  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/x/i/q/s-wx-d-pocket-102-grey-woxen-original-imagmb2ejntmmc2f.jpeg?q=70",
    _id: uuid(),
    title: "Collar casual shirt",
    author: "Shiv Khera",
    price: "429",
    categoryName: "Men",

    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/m/o/t/l-st1-vebnor-original-imagmsyxhvkrfjgz.jpeg?q=70",
    _id: uuid(),
    title: "Mandarin Collar shirt",
    author: "Webnor",
    price: "369",
    categoryName: "Men",

    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/kzn17680/shirt/0/q/o/l-logo-shirt-infinity-choice-original-imagbhwczbphzk5f.jpeg?q=70",
    _id: uuid(),
    title: "slim fit shirt",
    author: "Lee cross",
    price: "729",
    categoryName: "Men",

    ratting: "d",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/i/d/n/3xl-nsg-358-saabhi-original-imaghrb4t4wudgfp.jpeg?q=70",
    _id: uuid(),
    title: "Women printed Dress",
    author: "Sabhi",
    price: "369",
    categoryName: "Women",
    ratting: "a",
  },
  {
    src: "https://ha-clothing.netlify.app/static/media/i4.e3f4cbd9.webp",
    _id: uuid(),
    title: "INDIE PICKS",
    author: "Anahat Handblock Kurta",
    price: "369",
    categoryName: "Women",
    ratting: "d",
  },
  // for home product
  {
    src: "https://rukminim2.flixcart.com/image/612/612/xif0q/key-holder/y/6/l/8-printed-brown-radha-krishna-two-box-key-holder-khatu-crafts-original-imaghv7ngwdxyfyp.jpeg?q=70",
    _id: uuid(),
    title: "Tow box keys",
    author: "Radhekrisna",
    price: "169",
    categoryName: "Home",
    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/kjlrb0w0-0/rack-shelf/q/o/g/asw44422-xtenshion-crafts-original-imafz4xzstpgskcc.jpeg?q=70",
    _id: uuid(),
    title: "Flowers",
    author: "Ram hind ",
    price: "569",
    categoryName: "Home",
    ratting: "b",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/k44hksw0/wall-clock/3/z/n/403-403white-analog-kadio-original-imafn3chkfwasuqe.jpeg?q=70",
    _id: uuid(),
    title: "wall watch",
    author: "Radhekrisna",
    price: "1169",
    categoryName: "Home",
    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/kjlrb0w0-0/rack-shelf/q/o/g/asw44422-xtenshion-crafts-original-imafz4xzstpgskcc.jpeg?q=70",
    _id: uuid(),
    title: "Flowers",
    author: "Ram hind ",
    price: "569",
    categoryName: "Home",
    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/k44hksw0/wall-clock/3/z/n/403-403white-analog-kadio-original-imafn3chkfwasuqe.jpeg?q=70",
    _id: uuid(),
    title: "wall watch",
    author: "Radhekrisna",
    price: "1169",
    categoryName: "Home",
    ratting: "b",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/kjlrb0w0-0/rack-shelf/q/o/g/asw44422-xtenshion-crafts-original-imafz4xzstpgskcc.jpeg?q=70",
    _id: uuid(),
    title: "Flowers",
    author: "Ram hind ",
    price: "569",
    categoryName: "Home",
    ratting: "a",
  },
  {
    src: "https://rukminim2.flixcart.com/image/612/612/k44hksw0/wall-clock/3/z/n/403-403white-analog-kadio-original-imafn3chkfwasuqe.jpeg?q=70",
    _id: uuid(),
    title: "wall watch",
    author: "Radhekrisna",
    price: "1169",
    categoryName: "Home",
    ratting: "c",
  },
];
